service: the-compliquer-bot

frameworkVersion: "3"

configValidationMode: error

provider:
  name: aws
  runtime: provided.al2
  architecture: arm64

functions:
  telegram:
    handler: webhook
    environment:
      OPENAI_API_KEY: ${env:OPENAI_API_KEY}
      TELEGRAM_BOT_TOKEN: ${env:TELEGRAM_BOT_TOKEN}
    events:
      - httpApi:
          path: /
          method: post
